// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Context categories for content detection and action filtering
 */
export type ContextCategory = "Length" | "Mass" | "Volume" | "Temperature" | "Speed" | "Currency" | "Text" | "Time" | "General";
