// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Updated for Phase 1 & 2: Added Translate and ConvertCurrency with payloads

export type ActionType = { type: "Translate", payload: TranslatePayload } | { type: "ConvertCurrency", payload: CurrencyPayload } | { type: "TranslateEn" } | { type: "TranslateZh" } | { type: "TranslateEs" } | { type: "TranslateFr" } | { type: "TranslateDe" } | { type: "TranslateAr" } | { type: "TranslatePt" } | { type: "TranslateRu" } | { type: "TranslateJa" } | { type: "TranslateHi" } | { type: "TranslateIt" } | { type: "TranslateNl" } | { type: "TranslatePl" } | { type: "TranslateTr" } | { type: "TranslateHy" } | { type: "TranslateFa" } | { type: "TranslateVi" } | { type: "TranslateId" } | { type: "TranslateKo" } | { type: "TranslateBn" } | { type: "TranslateUr" } | { type: "TranslateTh" } | { type: "TranslateSv" } | { type: "TranslateDa" } | { type: "TranslateFi" } | { type: "TranslateHu" } | { type: "ConvertUsd" } | { type: "ConvertEur" } | { type: "ConvertGbp" } | { type: "ConvertJpy" } | { type: "ConvertAud" } | { type: "ConvertCad" } | { type: "ConvertChf" } | { type: "ConvertCny" } | { type: "ConvertInr" } | { type: "ConvertMxn" } | { type: "ConvertUnit", payload: { target: string } } | { type: "ConvertTime", payload: string } | { type: "FindSynonyms" } | { type: "FindAntonyms" } | { type: "BriefDefinition" } | { type: "ClearClipboardHistory" } | { type: "PauseClipboard" } | { type: "ResumeClipboard" } | { type: "CountWords" } | { type: "CountChars" } | { type: "ReadingTime" };

export type TranslatePayload = { target_lang: string, source_lang: string | null, };

export type CurrencyPayload = { target_currency: string, };

export type CaptureResult = { text: string, source: string, };

/**
 * A single clipboard history item
 */
export type ClipboardHistoryItem = { id: string, item_type: ClipboardItemType, content: string, preview: string, timestamp: string, source_app: string | null, };

/**
 * Type of clipboard content
 */
export type ClipboardItemType = "text" | "html" | "rtf" | "image";

export type CommandItem = { id: string, label: string, description: string | null, action_type: ActionType | null, widget_type: string | null, category: ContextCategory | null, };

/**
 * Context categories for content detection and action filtering
 */
export type ContextCategory = "Language" | "Length" | "Mass" | "Volume" | "Temperature" | "Speed" | "Currency" | "Text" | "Time" | "General";

export type ConvertCurrencyRequest = { amount: string, from: string, to: string, date: string | null, };

export type ConvertCurrencyResponse = { result: string, rate: string, timestamp: string, };

export type ConvertTimeRequest = { time_input: string, target_timezone: string, source_timezone: string | null, matched_keyword: string | null, };

export type ConvertTimeResponse = { source_time: string, target_time: string, offset_description: string, source_timezone: string, target_timezone: string, target_utc_offset: string, target_zone_abbr: string, relative_offset: string, date_change_indicator: string | null, source_zone_abbr: string, source_utc_offset: string, };

export type ConvertUnitsRequest = { amount: number, from_unit: string, to_unit: string, material: string | null, };

export type ConvertUnitsResponse = { result: number, from_unit: string, to_unit: string, };

export type CursorPosition = { x: number, y: number, };

export type DefinitionEntry = { part_of_speech: string, definition: string, example: string | null, };

export type ExecuteActionRequest = { action_type: ActionType, params: any, };

export type ExecuteActionResponse = { result: string, metadata: any, };

export type LogRequest = { level: string, message: string, };

export type LookupDefinitionRequest = { word: string, };

export type LookupDefinitionResponse = { word: string, phonetic: string | null, definitions: Array<DefinitionEntry>, synonyms: Array<string>, antonyms: Array<string>, };

export type OpenWidgetRequest = { widget: string, payload: any, };

export type ParsedTimeInput = { time_input: string, source_timezone: string | null, matched_keyword: string | null, };

export type ScreenBounds = { x: number, y: number, width: number, height: number, };

export type TextAnalysisRequest = { text: string, };

export type TextAnalysisResponse = { word_count: number, char_count: number, char_count_no_spaces: number, grapheme_count: number, line_count: number, reading_time_sec: number, };

export type TimezoneInfo = { label: string, iana_id: string, keywords: string, };

export type TranslateRequest = { text: string, source_lang: string | null, target_lang: string, provider: string | null, };

export type TranslateResponse = { translated: string, detected_source_lang: string | null, };

export type WindowPosition = { x: number, y: number, };
