// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 4: Production-ready - All variants use structured payloads
 */
export type ActionType = { "type": "Translate", "payload": TranslatePayload } | { "type": "ConvertCurrency", "payload": CurrencyPayload } | { "type": "ConvertTimeAction", "payload": TimePayload } | { "type": "AnalyzeText", "payload": TextAnalysisPayload } | { "type": "DefinitionAction", "payload": DefinitionPayload } | { "type": "ConvertUnit", "payload": { target: string, } };

export type CaptureResult = { text: string, source: string, };

/**
 * A single clipboard history item
 */
export type ClipboardHistoryItem = { id: string, item_type: ClipboardItemType, content: string, preview: string, timestamp: string, source_app: string | null, };

/**
 * Type of clipboard content
 */
export type ClipboardItemType = "text" | "html" | "rtf" | "image";

export type CommandItem = { id: string, label: string, description: string | null, action_type: ActionType | null, widget_type: string | null, category: ContextCategory | null, };

/**
 * Context categories for content detection and action filtering
 */
export type ContextCategory = "Length" | "Mass" | "Volume" | "Temperature" | "Speed" | "Currency" | "Text" | "Time" | "General";

export type ConvertCurrencyRequest = { amount: string, from: string, to: string, date: string | null, };

export type ConvertCurrencyResponse = { result: string, rate: string, timestamp: string, };

export type ConvertTimeRequest = { time_input: string, target_timezone: string, source_timezone: string | null, matched_keyword: string | null, };

export type ConvertTimeResponse = { source_time: string, target_time: string, offset_description: string, source_timezone: string, target_timezone: string, target_utc_offset: string, target_zone_abbr: string, relative_offset: string, date_change_indicator: string | null, source_zone_abbr: string, source_utc_offset: string, };

export type ConvertUnitPayload = { value: number, from_unit: string, target_unit: string, };

export type ConvertUnitsRequest = { amount: number, from_unit: string, to_unit: string, material: string | null, };

export type ConvertUnitsResponse = { result: number, formatted_result: string, from_unit: string, to_unit: string, };

/**
 * Payload for currency conversion actions (Phase 2)
 * Carries target currency code
 */
export type CurrencyPayload = { 
/**
 * Target currency code (e.g., "USD", "EUR", "GBP")
 */
target_currency: string, };

export type CursorPosition = { x: number, y: number, };

/**
 * Definition action types
 */
export type DefinitionAction = "FindSynonyms" | "FindAntonyms" | "BriefDefinition";

export type DefinitionEntry = { part_of_speech: string, definition: string, example: string | null, };

/**
 * Payload for definition lookup actions
 */
export type DefinitionPayload = { 
/**
 * Type of definition lookup to perform
 */
action: DefinitionAction, };

export type ExecuteActionRequest = { action_type: ActionType, params: any, };

export type ExecuteActionResponse = { result: string, metadata: any, };

export type GetUnitsResponse = { units: Array<UnitDTO>, };

export type LogRequest = { level: string, message: string, };

export type LookupDefinitionRequest = { word: string, };

export type LookupDefinitionResponse = { word: string, phonetic: string | null, definitions: Array<DefinitionEntry>, synonyms: Array<string>, antonyms: Array<string>, };

export type OpenWidgetRequest = { widget: string, payload: any, };

export type ParseUnitResponse = { amount: number, unit: string, category: string, };

export type ParsedTimeInput = { time_input: string, source_timezone: string | null, matched_keyword: string | null, };

export type ScreenBounds = { x: number, y: number, width: number, height: number, };

/**
 * Text analysis action types
 */
export type TextAnalysisAction = "CountWords" | "CountChars" | "ReadingTime";

/**
 * Payload for text analysis actions
 */
export type TextAnalysisPayload = { 
/**
 * Type of text analysis to perform
 */
action: TextAnalysisAction, };

export type TextAnalysisRequest = { text: string, };

export type TextAnalysisResponse = { word_count: number, char_count: number, char_count_no_spaces: number, grapheme_count: number, line_count: number, reading_time_sec: number, };

/**
 * Payload for time conversion actions
 */
export type TimePayload = { 
/**
 * Target timezone (IANA identifier)
 */
target_timezone: string, };

export type TimezoneInfo = { label: string, iana_id: string, keywords: string, };

/**
 * Payload for translation actions
 * Carries target language code and optional source language
 */
export type TranslatePayload = { 
/**
 * Target language code (e.g., "en", "es", "zh")
 */
target_lang: string, 
/**
 * Optional source language code (None = auto-detect)
 */
source_lang: string | null, };

export type TranslateRequest = { text: string, source_lang: string | null, target_lang: string, provider: string | null, };

export type TranslateResponse = { translated: string, detected_source_lang: string | null, };

export type UnitDTO = { id: string, label: string, category: string, };

export type WindowPosition = { x: number, y: number, };
