// Time Zone Converter - Constants Layer
// Single Source of Truth for all timezone data

/// Timezone data: (Label, IANA ID, Search Keywords)
pub const ALL_TIMEZONES: &[(&str, &str, &str)] = &[
    ("Afghanistan", "Asia/Kabul", "afghanistan asia kabul"),
    ("Albania", "Europe/Tirane", "albania europe tirane tirana"),
    ("Algeria", "Africa/Algiers", "algeria africa algiers"),
    ("Andorra", "Europe/Andorra", "andorra europe"),
    ("Angola", "Africa/Luanda", "angola africa luanda"),
    ("Antigua and Barbuda", "America/Antigua", "antigua barbuda america caribbean"),
    ("Argentina", "America/Argentina/Buenos_Aires", "argentina america buenos aires"),
    ("Armenia", "Asia/Yerevan", "armenia asia yerevan"),
    ("Australia", "Australia/Sydney", "australia sydney canberra pacific"),
    ("Austria", "Europe/Vienna", "austria europe vienna"),
    ("Azerbaijan", "Asia/Baku", "azerbaijan asia baku"),
    ("Bahamas", "America/Nassau", "bahamas america nassau caribbean"),
    ("Bahrain", "Asia/Bahrain", "bahrain asia middle east"),
    ("Bangladesh", "Asia/Dhaka", "bangladesh asia dhaka"),
    ("Barbados", "America/Barbados", "barbados america caribbean"),
    ("Belarus", "Europe/Minsk", "belarus europe minsk"),
    ("Belgium", "Europe/Brussels", "belgium europe brussels"),
    ("Belize", "America/Belize", "belize america central"),
    ("Benin", "Africa/Porto-Novo", "benin africa porto novo"),
    ("Bhutan", "Asia/Thimphu", "bhutan asia thimphu"),
    ("Bolivia", "America/La_Paz", "bolivia america la paz"),
    ("Bosnia and Herzegovina", "Europe/Sarajevo", "bosnia herzegovina europe sarajevo"),
    ("Botswana", "Africa/Gaborone", "botswana africa gaborone"),
    ("Brazil", "America/Sao_Paulo", "brazil america sao paulo brasilia"),
    ("Brunei", "Asia/Brunei", "brunei asia"),
    ("Bulgaria", "Europe/Sofia", "bulgaria europe sofia"),
    ("Burkina Faso", "Africa/Ouagadougou", "burkina faso africa ouagadougou"),
    ("Burundi", "Africa/Bujumbura", "burundi africa bujumbura"),
    ("Cabo Verde", "Atlantic/Cape_Verde", "cabo verde cape atlantic"),
    ("Cambodia", "Asia/Phnom_Penh", "cambodia asia phnom penh"),
    ("Cameroon", "Africa/Douala", "cameroon africa douala"),
    ("Canada", "America/Toronto", "canada america toronto ottawa"),
    ("Central African Republic", "Africa/Bangui", "central african republic africa bangui"),
    ("Chad", "Africa/Ndjamena", "chad africa ndjamena"),
    ("Chile", "America/Santiago", "chile america santiago"),
    ("China", "Asia/Shanghai", "china asia shanghai beijing"),
    ("Colombia", "America/Bogota", "colombia america bogota"),
    ("Comoros", "Indian/Comoro", "comoros indian ocean"),
    ("Congo (Republic)", "Africa/Brazzaville", "congo republic africa brazzaville"),
    ("Costa Rica", "America/Costa_Rica", "costa rica america central"),
    ("Croatia", "Europe/Zagreb", "croatia europe zagreb"),
    ("Cuba", "America/Havana", "cuba america havana caribbean"),
    ("Cyprus", "Asia/Nicosia", "cyprus asia nicosia"),
    ("Czech Republic", "Europe/Prague", "czech republic europe prague"),
    ("Denmark", "Europe/Copenhagen", "denmark europe copenhagen"),
    ("Djibouti", "Africa/Djibouti", "djibouti africa"),
    ("Dominica", "America/Dominica", "dominica america caribbean"),
    ("Dominican Republic", "America/Santo_Domingo", "dominican republic america santo domingo caribbean"),
    ("DR Congo", "Africa/Kinshasa", "dr congo democratic republic africa kinshasa"),
    ("Ecuador", "America/Guayaquil", "ecuador america guayaquil quito"),
    ("Egypt", "Africa/Cairo", "egypt africa cairo"),
    ("El Salvador", "America/El_Salvador", "el salvador america central"),
    ("Equatorial Guinea", "Africa/Malabo", "equatorial guinea africa malabo"),
    ("Eritrea", "Africa/Asmara", "eritrea africa asmara"),
    ("Estonia", "Europe/Tallinn", "estonia europe tallinn"),
    ("Eswatini", "Africa/Mbabane", "eswatini swaziland africa mbabane"),
    ("Ethiopia", "Africa/Addis_Ababa", "ethiopia africa addis ababa"),
    ("Fiji", "Pacific/Fiji", "fiji pacific"),
    ("Finland", "Europe/Helsinki", "finland europe helsinki"),
    ("France", "Europe/Paris", "france europe paris"),
    ("Gabon", "Africa/Libreville", "gabon africa libreville"),
    ("Gambia", "Africa/Banjul", "gambia africa banjul"),
    ("Georgia", "Asia/Tbilisi", "georgia asia tbilisi"),
    ("Germany", "Europe/Berlin", "germany europe berlin"),
    ("Ghana", "Africa/Accra", "ghana africa accra"),
    ("Greece", "Europe/Athens", "greece europe athens"),
    ("Grenada", "America/Grenada", "grenada america caribbean"),
    ("Guatemala", "America/Guatemala", "guatemala america central"),
    ("Guinea", "Africa/Conakry", "guinea africa conakry"),
    ("Guinea-Bissau", "Africa/Bissau", "guinea bissau africa"),
    ("Guyana", "America/Guyana", "guyana america south"),
    ("Haiti", "America/Port-au-Prince", "haiti america port au prince caribbean"),
    ("Honduras", "America/Tegucigalpa", "honduras america tegucigalpa central"),
    ("Hungary", "Europe/Budapest", "hungary europe budapest"),
    ("Iceland", "Atlantic/Reykjavik", "iceland atlantic reykjavik"),
    ("India", "Asia/Kolkata", "india asia kolkata calcutta new delhi"),
    ("Indonesia", "Asia/Jakarta", "indonesia asia jakarta"),
    ("Iran", "Asia/Tehran", "iran asia tehran"),
    ("Iraq", "Asia/Baghdad", "iraq asia baghdad"),
    ("Ireland", "Europe/Dublin", "ireland europe dublin"),
    ("Israel", "Asia/Jerusalem", "israel asia jerusalem"),
    ("Italy", "Europe/Rome", "italy europe rome"),
    ("Jamaica", "America/Jamaica", "jamaica america caribbean"),
    ("Japan", "Asia/Tokyo", "japan asia tokyo"),
    ("Jordan", "Asia/Amman", "jordan asia amman"),
    ("Kazakhstan", "Asia/Almaty", "kazakhstan asia almaty astana"),
    ("Kenya", "Africa/Nairobi", "kenya africa nairobi"),
    ("Kiribati", "Pacific/Tarawa", "kiribati pacific tarawa"),
    ("Kuwait", "Asia/Kuwait", "kuwait asia middle east"),
    ("Kyrgyzstan", "Asia/Bishkek", "kyrgyzstan asia bishkek"),
    ("Laos", "Asia/Vientiane", "laos asia vientiane"),
    ("Latvia", "Europe/Riga", "latvia europe riga"),
    ("Lebanon", "Asia/Beirut", "lebanon asia beirut"),
    ("Lesotho", "Africa/Maseru", "lesotho africa maseru"),
    ("Liberia", "Africa/Monrovia", "liberia africa monrovia"),
    ("Libya", "Africa/Tripoli", "libya africa tripoli"),
    ("Liechtenstein", "Europe/Vaduz", "liechtenstein europe vaduz"),
    ("Lithuania", "Europe/Vilnius", "lithuania europe vilnius"),
    ("Luxembourg", "Europe/Luxembourg", "luxembourg europe"),
    ("Madagascar", "Indian/Antananarivo", "madagascar indian antananarivo"),
    ("Malawi", "Africa/Blantyre", "malawi africa blantyre"),
    ("Malaysia", "Asia/Kuala_Lumpur", "malaysia asia kuala lumpur"),
    ("Maldives", "Indian/Maldives", "maldives indian ocean"),
    ("Mali", "Africa/Bamako", "mali africa bamako"),
    ("Malta", "Europe/Malta", "malta europe"),
    ("Marshall Islands", "Pacific/Majuro", "marshall islands pacific majuro"),
    ("Mauritania", "Africa/Nouakchott", "mauritania africa nouakchott"),
    ("Mauritius", "Indian/Mauritius", "mauritius indian ocean"),
    ("Mexico", "America/Mexico_City", "mexico america mexico city"),
    ("Micronesia", "Pacific/Pohnpei", "micronesia pacific pohnpei palikir"),
    ("Moldova", "Europe/Chisinau", "moldova europe chisinau"),
    ("Monaco", "Europe/Monaco", "monaco europe"),
    ("Mongolia", "Asia/Ulaanbaatar", "mongolia asia ulaanbaatar ulan bator"),
    ("Montenegro", "Europe/Podgorica", "montenegro europe podgorica"),
    ("Morocco", "Africa/Casablanca", "morocco africa casablanca"),
    ("Mozambique", "Africa/Maputo", "mozambique africa maputo"),
    ("Myanmar", "Asia/Yangon", "myanmar burma asia yangon rangoon"),
    ("Namibia", "Africa/Windhoek", "namibia africa windhoek"),
    ("Nauru", "Pacific/Nauru", "nauru pacific"),
    ("Nepal", "Asia/Kathmandu", "nepal asia kathmandu"),
    ("Netherlands", "Europe/Amsterdam", "netherlands holland europe amsterdam"),
    ("New Zealand", "Pacific/Auckland", "new zealand pacific auckland wellington"),
    ("Nicaragua", "America/Managua", "nicaragua america managua central"),
    ("Niger", "Africa/Niamey", "niger africa niamey"),
    ("Nigeria", "Africa/Lagos", "nigeria africa lagos"),
    ("North Korea", "Asia/Pyongyang", "north korea asia pyongyang dprk"),
    ("North Macedonia", "Europe/Skopje", "north macedonia europe skopje"),
    ("Norway", "Europe/Oslo", "norway europe oslo"),
    ("Oman", "Asia/Muscat", "oman asia muscat"),
    ("Pakistan", "Asia/Karachi", "pakistan asia karachi islamabad"),
    ("Palau", "Pacific/Palau", "palau pacific"),
    ("Palestine", "Asia/Hebron", "palestine asia hebron ramallah"),
    ("Panama", "America/Panama", "panama america central"),
    ("Papua New Guinea", "Pacific/Port_Moresby", "papua new guinea pacific port moresby"),
    ("Paraguay", "America/Asuncion", "paraguay america asuncion"),
    ("Peru", "America/Lima", "peru america lima"),
    ("Philippines", "Asia/Manila", "philippines asia manila"),
    ("Poland", "Europe/Warsaw", "poland europe warsaw"),
    ("Portugal", "Europe/Lisbon", "portugal europe lisbon"),
    ("Qatar", "Asia/Qatar", "qatar asia middle east"),
    ("Romania", "Europe/Bucharest", "romania europe bucharest"),
    ("Russia", "Europe/Moscow", "russia europe moscow"),
    ("Rwanda", "Africa/Kigali", "rwanda africa kigali"),
    ("Saint Kitts and Nevis", "America/St_Kitts", "saint kitts nevis america caribbean"),
    ("Saint Lucia", "America/St_Lucia", "saint lucia america caribbean"),
    ("Saint Vincent and the Grenadines", "America/St_Vincent", "saint vincent grenadines america caribbean"),
    ("Samoa", "Pacific/Apia", "samoa pacific apia"),
    ("San Marino", "Europe/San_Marino", "san marino europe"),
    ("Saudi Arabia", "Asia/Riyadh", "saudi arabia asia riyadh"),
    ("Senegal", "Africa/Dakar", "senegal africa dakar"),
    ("Serbia", "Europe/Belgrade", "serbia europe belgrade"),
    ("Seychelles", "Indian/Mahe", "seychelles indian mahe"),
    ("Sierra Leone", "Africa/Freetown", "sierra leone africa freetown"),
    ("Singapore", "Asia/Singapore", "singapore asia"),
    ("Slovakia", "Europe/Bratislava", "slovakia europe bratislava"),
    ("Slovenia", "Europe/Ljubljana", "slovenia europe ljubljana"),
    ("Solomon Islands", "Pacific/Guadalcanal", "solomon islands pacific guadalcanal"),
    ("Somalia", "Africa/Mogadishu", "somalia africa mogadishu"),
    ("South Africa", "Africa/Johannesburg", "south africa johannesburg pretoria"),
    ("South Korea", "Asia/Seoul", "south korea asia seoul"),
    ("South Sudan", "Africa/Juba", "south sudan africa juba"),
    ("Spain", "Europe/Madrid", "spain europe madrid"),
    ("Sri Lanka", "Asia/Colombo", "sri lanka asia colombo"),
    ("Sudan", "Africa/Khartoum", "sudan africa khartoum"),
    ("Suriname", "America/Paramaribo", "suriname america paramaribo"),
    ("Sweden", "Europe/Stockholm", "sweden europe stockholm"),
    ("Switzerland", "Europe/Zurich", "switzerland europe zurich"),
    ("Syria", "Asia/Damascus", "syria asia damascus"),
    ("Taiwan", "Asia/Taipei", "taiwan asia taipei"),
    ("Tajikistan", "Asia/Dushanbe", "tajikistan asia dushanbe"),
    ("Tanzania", "Africa/Dar_es_Salaam", "tanzania africa dar es salaam"),
    ("Thailand", "Asia/Bangkok", "thailand asia bangkok"),
    ("Timor-Leste", "Asia/Dili", "timor leste east asia dili"),
    ("Togo", "Africa/Lome", "togo africa lome"),
    ("Tonga", "Pacific/Tongatapu", "tonga pacific tongatapu"),
    ("Trinidad and Tobago", "America/Port_of_Spain", "trinidad tobago america port spain caribbean"),
    ("Tunisia", "Africa/Tunis", "tunisia africa tunis"),
    ("Turkey", "Europe/Istanbul", "turkey europe istanbul"),
    ("Turkmenistan", "Asia/Ashgabat", "turkmenistan asia ashgabat"),
    ("Tuvalu", "Pacific/Funafuti", "tuvalu pacific funafuti"),
    ("Uganda", "Africa/Kampala", "uganda africa kampala"),
    ("Ukraine", "Europe/Kiev", "ukraine europe kiev kyiv"),
    ("United Arab Emirates", "Asia/Dubai", "uae united arab emirates asia dubai"),
    ("United Kingdom", "Europe/London", "uk united kingdom great britain europe london"),
    ("United States", "America/New_York", "usa united states america new york washington dc"),
    ("Uruguay", "America/Montevideo", "uruguay america montevideo"),
    ("Uzbekistan", "Asia/Tashkent", "uzbekistan asia tashkent"),
    ("Vanuatu", "Pacific/Efate", "vanuatu pacific efate"),
    ("Vatican City", "Europe/Vatican", "vatican city europe"),
    ("Venezuela", "America/Caracas", "venezuela america caracas"),
    ("Vietnam", "Asia/Ho_Chi_Minh", "vietnam asia ho chi minh saigon hanoi"),
    ("Yemen", "Asia/Aden", "yemen asia aden"),
    ("Zambia", "Africa/Lusaka", "zambia africa lusaka"),
    ("Zimbabwe", "Africa/Harare", "zimbabwe africa harare"),
];

/// Timezone IANA ID to Abbreviation mapping
/// Format: (IANA_ID, Abbreviation)
pub const TIMEZONE_ABBREVIATIONS_MAP: &[(&str, &str)] = &[
    ("Asia/Kabul", "AFT"),
    ("Europe/Tirane", "CET"),
    ("Africa/Algiers", "CET"),
    ("Europe/Andorra", "CET"),
    ("Africa/Luanda", "WAT"),
    ("America/Antigua", "AST"),
    ("America/Argentina/Buenos_Aires", "ART"),
    ("Asia/Yerevan", "AMT"),
    ("Australia/Sydney", "AEDT"),
    ("Europe/Vienna", "CET"),
    ("Asia/Baku", "AZT"),
    ("America/Nassau", "EST"),
    ("Asia/Bahrain", "AST"),
    ("Asia/Dhaka", "BST"),
    ("America/Barbados", "AST"),
    ("Europe/Minsk", "MSK"),
    ("Europe/Brussels", "CET"),
    ("America/Belize", "CST"),
    ("Africa/Porto-Novo", "WAT"),
    ("Asia/Thimphu", "BTT"),
    ("America/La_Paz", "BOT"),
    ("Europe/Sarajevo", "CET"),
    ("Africa/Gaborone", "CAT"),
    ("America/Sao_Paulo", "BRT"),
    ("Asia/Brunei", "BNT"),
    ("Europe/Sofia", "EET"),
    ("Africa/Ouagadougou", "GMT"),
    ("Africa/Bujumbura", "CAT"),
    ("Atlantic/Cape_Verde", "CVT"),
    ("Asia/Phnom_Penh", "ICT"),
    ("Africa/Douala", "WAT"),
    ("America/Toronto", "EST"),
    ("Africa/Bangui", "WAT"),
    ("Africa/Ndjamena", "WAT"),
    ("America/Santiago", "CLT"),
    ("Asia/Shanghai", "CST"),
    ("America/Bogota", "COT"),
    ("Indian/Comoro", "EAT"),
    ("Africa/Brazzaville", "WAT"),
    ("America/Costa_Rica", "CST"),
    ("Europe/Zagreb", "CET"),
    ("America/Havana", "CST"),
    ("Asia/Nicosia", "EET"),
    ("Europe/Prague", "CET"),
    ("Europe/Copenhagen", "CET"),
    ("Africa/Djibouti", "EAT"),
    ("America/Dominica", "AST"),
    ("America/Santo_Domingo", "AST"),
    ("Africa/Kinshasa", "WAT"),
    ("America/Guayaquil", "ECT"),
    ("Africa/Cairo", "EET"),
    ("America/El_Salvador", "CST"),
    ("Africa/Malabo", "WAT"),
    ("Africa/Asmara", "EAT"),
    ("Europe/Tallinn", "EET"),
    ("Africa/Mbabane", "SAST"),
    ("Africa/Addis_Ababa", "EAT"),
    ("Pacific/Fiji", "FJT"),
    ("Europe/Helsinki", "EET"),
    ("Europe/Paris", "CET"),
    ("Africa/Libreville", "WAT"),
    ("Africa/Banjul", "GMT"),
    ("Asia/Tbilisi", "GET"),
    ("Europe/Berlin", "CET"),
    ("Africa/Accra", "GMT"),
    ("Europe/Athens", "EET"),
    ("America/Grenada", "AST"),
    ("America/Guatemala", "CST"),
    ("Africa/Conakry", "GMT"),
    ("Africa/Bissau", "GMT"),
    ("America/Guyana", "GYT"),
    ("America/Port-au-Prince", "EST"),
    ("America/Tegucigalpa", "CST"),
    ("Europe/Budapest", "CET"),
    ("Atlantic/Reykjavik", "GMT"),
    ("Asia/Kolkata", "IST"),
    ("Asia/Jakarta", "WIB"),
    ("Asia/Tehran", "IRST"),
    ("Asia/Baghdad", "AST"),
    ("Europe/Dublin", "GMT"),
    ("Asia/Jerusalem", "IST"),
    ("Europe/Rome", "CET"),
    ("America/Jamaica", "EST"),
    ("Asia/Tokyo", "JST"),
    ("Asia/Amman", "EET"),
    ("Asia/Almaty", "ALMT"),
    ("Africa/Nairobi", "EAT"),
    ("Pacific/Tarawa", "GILT"),
    ("Asia/Kuwait", "AST"),
    ("Asia/Bishkek", "KGT"),
    ("Asia/Vientiane", "ICT"),
    ("Europe/Riga", "EET"),
    ("Asia/Beirut", "EET"),
    ("Africa/Maseru", "SAST"),
    ("Africa/Monrovia", "GMT"),
    ("Africa/Tripoli", "EET"),
    ("Europe/Vaduz", "CET"),
    ("Europe/Vilnius", "EET"),
    ("Europe/Luxembourg", "CET"),
    ("Indian/Antananarivo", "EAT"),
    ("Africa/Blantyre", "CAT"),
    ("Asia/Kuala_Lumpur", "MYT"),
    ("Indian/Maldives", "MVT"),
    ("Africa/Bamako", "GMT"),
    ("Europe/Malta", "CET"),
    ("Pacific/Majuro", "MHT"),
    ("Africa/Nouakchott", "GMT"),
    ("Indian/Mauritius", "MUT"),
    ("America/Mexico_City", "CST"),
    ("Pacific/Pohnpei", "PONT"),
    ("Europe/Chisinau", "EET"),
    ("Europe/Monaco", "CET"),
    ("Asia/Ulaanbaatar", "ULAT"),
    ("Europe/Podgorica", "CET"),
    ("Africa/Casablanca", "WET"),
    ("Africa/Maputo", "CAT"),
    ("Asia/Yangon", "MMT"),
    ("Africa/Windhoek", "CAT"),
    ("Pacific/Nauru", "NRT"),
    ("Asia/Kathmandu", "NPT"),
    ("Europe/Amsterdam", "CET"),
    ("Pacific/Auckland", "NZDT"),
    ("America/Managua", "CST"),
    ("Africa/Niamey", "WAT"),
    ("Africa/Lagos", "WAT"),
    ("Asia/Pyongyang", "KST"),
    ("Europe/Skopje", "CET"),
    ("Europe/Oslo", "CET"),
    ("Asia/Muscat", "GST"),
    ("Asia/Karachi", "PKT"),
    ("Pacific/Palau", "PWT"),
    ("Asia/Hebron", "EET"),
    ("America/Panama", "EST"),
    ("Pacific/Port_Moresby", "PGT"),
    ("America/Asuncion", "PYT"),
    ("America/Lima", "PET"),
    ("Asia/Manila", "PHT"),
    ("Europe/Warsaw", "CET"),
    ("Europe/Lisbon", "WET"),
    ("Asia/Qatar", "AST"),
    ("Europe/Bucharest", "EET"),
    ("Europe/Moscow", "MSK"),
    ("Africa/Kigali", "CAT"),
    ("America/St_Kitts", "AST"),
    ("America/St_Lucia", "AST"),
    ("America/St_Vincent", "AST"),
    ("Pacific/Apia", "WST"),
    ("Europe/San_Marino", "CET"),
    ("Asia/Riyadh", "AST"),
    ("Africa/Dakar", "GMT"),
    ("Europe/Belgrade", "CET"),
    ("Indian/Mahe", "SCT"),
    ("Africa/Freetown", "GMT"),
    ("Asia/Singapore", "SGT"),
    ("Europe/Bratislava", "CET"),
    ("Europe/Ljubljana", "CET"),
    ("Pacific/Guadalcanal", "SBT"),
    ("Africa/Mogadishu", "EAT"),
    ("Africa/Johannesburg", "SAST"),
    ("Asia/Seoul", "KST"),
    ("Africa/Juba", "EAT"),
    ("Europe/Madrid", "CET"),
    ("Asia/Colombo", "IST"),
    ("Africa/Khartoum", "CAT"),
    ("America/Paramaribo", "SRT"),
    ("Europe/Stockholm", "CET"),
    ("Europe/Zurich", "CET"),
    ("Asia/Damascus", "EET"),
    ("Asia/Taipei", "CST"),
    ("Asia/Dushanbe", "TJT"),
    ("Africa/Dar_es_Salaam", "EAT"),
    ("Asia/Bangkok", "ICT"),
    ("Asia/Dili", "TLT"),
    ("Africa/Lome", "GMT"),
    ("Pacific/Tongatapu", "TOT"),
    ("America/Port_of_Spain", "AST"),
    ("Africa/Tunis", "CET"),
    ("Europe/Istanbul", "TRT"),
    ("Asia/Ashgabat", "TMT"),
    ("Pacific/Funafuti", "TVT"),
    ("Africa/Kampala", "EAT"),
    ("Europe/Kiev", "EET"),
    ("Asia/Dubai", "GST"),
    ("Europe/London", "GMT"),
    ("America/New_York", "EST"),
    ("America/Montevideo", "UYT"),
    ("Asia/Tashkent", "UZT"),
    ("Pacific/Efate", "VUT"),
    ("Europe/Vatican", "CET"),
    ("America/Caracas", "VET"),
    ("Asia/Ho_Chi_Minh", "ICT"),
    ("Asia/Aden", "AST"),
    ("Africa/Lusaka", "CAT"),
    ("Africa/Harare", "CAT"),
];

/// Get timezone abbreviation for a given IANA ID
pub fn get_timezone_abbreviation(iana_id: &str) -> &str {
    TIMEZONE_ABBREVIATIONS_MAP
        .iter()
        .find(|(id, _)| *id == iana_id)
        .map(|(_, abbr)| *abbr)
        .unwrap_or("UTC")
}
