// Time Zone Converter - Constants Layer
// Single Source of Truth for all timezone data

/// Timezone data: (Label, IANA ID, Search Keywords)
pub const ALL_TIMEZONES: &[(&str, &str, &str)] = &[
    // --- ASIA ---
    ("Beijing/China", "Asia/Shanghai", "china beijing shanghai shenzhen guangzhou chengdu chongqing wuhan tianjin hangzhou nanjing xi'an harbin shenyang urumqi lhasa hong kong macau"),
    ("Tokyo/Japan", "Asia/Tokyo", "japan tokyo osaka kyoto yokohama sapporo nagoya kobe fukuoka kawasaki"),
    ("New Delhi/India", "Asia/Kolkata", "india delhi mumbai bengaluru bangalore chennai kolkata calcutta hyderabad ahmedabad pune jaipur kochi patna nagpur guwahati"),
    ("Seoul/South Korea", "Asia/Seoul", "south korea seoul busan incheon daegu daejeon gwangju"),
    ("Singapore/Singapore", "Asia/Singapore", "singapore"),
    ("Dubai/United Arab Emirates", "Asia/Dubai", "uae united arab emirates dubai abu dhabi sharjah"),
    ("Bangkok/Thailand", "Asia/Bangkok", "thailand bangkok chiang mai phuket"),
    ("Jakarta/Indonesia", "Asia/Jakarta", "indonesia jakarta surabaya bandung"),
    ("Kabul/Afghanistan", "Asia/Kabul", "afghanistan asia kabul"),
    ("Yerevan/Armenia", "Asia/Yerevan", "armenia asia yerevan"),
    ("Dhaka/Bangladesh", "Asia/Dhaka", "bangladesh asia dhaka"),
    ("Thimphu/Bhutan", "Asia/Thimphu", "bhutan asia thimphu"),
    ("Baghdad/Iraq", "Asia/Baghdad", "iraq asia baghdad"),
    ("Jerusalem/Israel", "Asia/Jerusalem", "israel asia jerusalem"),
    ("Amman/Jordan", "Asia/Amman", "jordan asia amman"),
    ("Almaty/Kazakhstan", "Asia/Almaty", "kazakhstan asia almaty astana"),
    ("Kuwait/Kuwait", "Asia/Kuwait", "kuwait asia middle east"),
    ("Bishkek/Kyrgyzstan", "Asia/Bishkek", "kyrgyzstan asia bishkek"),
    ("Vientiane/Laos", "Asia/Vientiane", "laos asia vientiane"),
    ("Beirut/Lebanon", "Asia/Beirut", "lebanon asia beirut"),
    ("Kuala Lumpur/Malaysia", "Asia/Kuala_Lumpur", "malaysia asia kuala lumpur"),
    ("Colombo/Sri Lanka", "Asia/Colombo", "sri lanka asia colombo"),
    ("Manila/Philippines", "Asia/Manila", "philippines asia manila"),
    ("Muscat/Oman", "Asia/Muscat", "oman asia muscat"),
    ("Karachi/Pakistan", "Asia/Karachi", "pakistan asia karachi islamabad"),
    ("Tehran/Iran", "Asia/Tehran", "iran tehran mashhad isfahan karaj shiraz"),
    ("Riyadh/Saudi Arabia", "Asia/Riyadh", "saudi arabia riyadh jeddah mecca medina"),
    ("Dushanbe/Tajikistan", "Asia/Dushanbe", "tajikistan asia dushanbe"),
    ("Ashgabat/Turkmenistan", "Asia/Ashgabat", "turkmenistan asia ashgabat"),
    ("Tashkent/Uzbekistan", "Asia/Tashkent", "uzbekistan asia tashkent"),
    ("Aden/Yemen", "Asia/Aden", "yemen asia aden"),
    ("Yangon/Myanmar", "Asia/Yangon", "myanmar burma asia yangon rangoon"),
    ("Dili/Timor-Leste", "Asia/Dili", "timor leste east asia dili"),
    ("Pyongyang/North Korea", "Asia/Pyongyang", "north korea asia pyongyang dprk"),
    ("Ho Chi Minh/Vietnam", "Asia/Ho_Chi_Minh", "vietnam asia ho chi minh saigon hanoi"),

    // --- EUROPE ---
    ("London/United Kingdom", "Europe/London", "uk united kingdom great britain england scotland wales london manchester birmingham liverpool edinburgh glasgow belfast leeds sheffield bristol newcastle cardiff"),
    ("Paris/France", "Europe/Paris", "france paris marseille lyon toulouse nice nantes strasbourg montpellier bordeaux lille"),
    ("Berlin/Germany", "Europe/Berlin", "germany berlin hamburg munich cologne frankfurt stuttgart dusseldorf dortmund essen leipzig"),
    ("Rome/Italy", "Europe/Rome", "italy rome milan naples turin palermo genoa bologna florence"),
    ("Madrid/Spain", "Europe/Madrid", "spain madrid barcelona valencia seville zaragoza malaga"),
    ("Moscow/Russia", "Europe/Moscow", "russia moscow st petersburg novosibirsk yekaterinburg kazan nizhny novgorod chelyabinsk samara omsk"),
    ("Amsterdam/Netherlands", "Europe/Amsterdam", "netherlands amsterdam rotterdam the hague utrecht"),
    ("Zurich/Switzerland", "Europe/Zurich", "switzerland zurich geneva basel lausanne bern"),
    ("Kyiv/Ukraine", "Europe/Kiev", "ukraine kyiv kiev kharkiv odessa dnipro donetsk zaporizhzhia lviv"),
    ("Tirane/Albania", "Europe/Tirane", "albania europe tirane tirana"),
    ("Vienna/Austria", "Europe/Vienna", "austria europe vienna"),
    ("Andorra la Vella/Andorra", "Europe/Andorra", "andorra europe"),
    ("Sarajevo/Bosnia and Herzegovina", "Europe/Sarajevo", "bosnia herzegovina europe sarajevo"),
    ("Sofia/Bulgaria", "Europe/Sofia", "bulgaria europe sofia"),
    ("Zagreb/Croatia", "Europe/Zagreb", "croatia europe zagreb"),
    ("Prague/Czech Republic", "Europe/Prague", "czech republic europe prague"),
    ("Copenhagen/Denmark", "Europe/Copenhagen", "denmark europe copenhagen"),
    ("Tallinn/Estonia", "Europe/Tallinn", "estonia europe tallinn"),
    ("Helsinki/Finland", "Europe/Helsinki", "finland europe helsinki"),
    ("Athens/Greece", "Europe/Athens", "greece europe athens"),
    ("Budapest/Hungary", "Europe/Budapest", "hungary europe budapest"),
    ("Reykjavik/Iceland", "Atlantic/Reykjavik", "iceland atlantic reykjavik"),
    ("Riga/Latvia", "Europe/Riga", "latvia europe riga"),
    ("Vaduz/Liechtenstein", "Europe/Vaduz", "liechtenstein europe vaduz"),
    ("Vilnius/Lithuania", "Europe/Vilnius", "lithuania europe vilnius"),
    ("Luxembourg/Luxembourg", "Europe/Luxembourg", "luxembourg europe"),
    ("Valletta/Malta", "Europe/Malta", "malta europe"),
    ("Chisinau/Moldova", "Europe/Chisinau", "moldova europe chisinau"),
    ("Monaco/Monaco", "Europe/Monaco", "monaco europe"),
    ("Podgorica/Montenegro", "Europe/Podgorica", "montenegro europe podgorica"),
    ("Oslo/Norway", "Europe/Oslo", "norway europe oslo"),
    ("Skopje/North Macedonia", "Europe/Skopje", "north macedonia europe skopje"),
    ("Lisbon/Portugal", "Europe/Lisbon", "portugal europe lisbon"),
    ("Bucharest/Romania", "Europe/Bucharest", "romania europe bucharest"),
    ("San Marino/San Marino", "Europe/San_Marino", "san marino europe"),
    ("Belgrade/Serbia", "Europe/Belgrade", "serbia europe belgrade"),
    ("Bratislava/Slovakia", "Europe/Bratislava", "slovakia europe bratislava"),
    ("Ljubljana/Slovenia", "Europe/Ljubljana", "slovenia europe ljubljana"),
    ("Stockholm/Sweden", "Europe/Stockholm", "sweden europe stockholm"),
    ("Vatican City/Vatican", "Europe/Vatican", "vatican city europe"),
    ("Istanbul/Turkey", "Europe/Istanbul", "turkey istanbul ankara izmir bursa adana"),

    // --- AMERICAS ---
    ("New York/United States", "America/New_York", "usa united states eastern est edt new york nyc washington dc miami atlanta boston philadelphia detroit indianapolis louisville monticello columbus charlotte orlando"),
    ("Chicago/United States", "America/Chicago", "usa united states central cst cdt chicago houston dallas austin san antonio nashville memphis kansas city minneapolis st louis new orleans"),
    ("Denver/United States", "America/Denver", "usa united states mountain mst mdt denver salt lake city albuquerque el paso"),
    ("Phoenix/United States", "America/Phoenix", "usa united states arizona phoenix tucson flagstaff"),
    ("Los Angeles/United States", "America/Los_Angeles", "usa united states pacific pst pdt los angeles la san francisco sf san diego seattle portland las vegas vancouver sacramento san jose"),
    ("Anchorage/United States", "America/Anchorage", "usa united states alaska anchorage juneau fairbanks"),
    ("Honolulu/United States", "Pacific/Honolulu", "usa united states hawaii honolulu adak hilo"),
    ("Toronto/Canada", "America/Toronto", "canada eastern toronto montreal ottawa quebec city hamilton london"),
    ("Vancouver/Canada", "America/Vancouver", "canada pacific vancouver victoria surrey burnaby"),
    ("Sao Paulo/Brazil", "America/Sao_Paulo", "brazil sao paulo rio de janeiro brasilia salvador fortaleza belo horizonte"),
    ("Buenos Aires/Argentina", "America/Argentina/Buenos_Aires", "argentina america buenos aires"),
    ("Antigua/Antigua and Barbuda", "America/Antigua", "antigua barbuda america caribbean"),
    ("Nassau/Bahamas", "America/Nassau", "bahamas america nassau caribbean"),
    ("Managua/Nicaragua", "America/Managua", "nicaragua america managua central"),
    ("Mexico City/Mexico", "America/Mexico_City", "mexico america mexico city"),
    ("Guatemala/Guatemala", "America/Guatemala", "guatemala america central"),
    ("Havana/Cuba", "America/Havana", "cuba america havana caribbean"),
    ("Port of Spain/Trinidad and Tobago", "America/Port_of_Spain", "trinidad tobago america port spain caribbean"),
    ("Paramaribo/Suriname", "America/Paramaribo", "suriname america paramaribo"),
    ("Caracas/Venezuela", "America/Caracas", "venezuela america caracas"),
    ("Montevideo/Uruguay", "America/Montevideo", "uruguay america montevideo"),
    ("Asuncion/Paraguay", "America/Asuncion", "paraguay america asuncion"),
    ("Lima/Peru", "America/Lima", "peru america lima"),
    ("Bogota/Colombia", "America/Bogota", "colombia america bogota"),
    ("Guayaquil/Ecuador", "America/Guayaquil", "ecuador america guayaquil quito"),
    ("Port-au-Prince/Haiti", "America/Port-au-Prince", "haiti america port au prince caribbean"),
    ("Tegucigalpa/Honduras", "America/Tegucigalpa", "honduras america tegucigalpa central"),
    ("Belize City/Belize", "America/Belize", "belize america central"),
    ("St Kitts/Saint Kitts and Nevis", "America/St_Kitts", "saint kitts nevis america caribbean"),
    ("Castries/Saint Lucia", "America/St_Lucia", "saint lucia america caribbean"),
    ("Kingstown/Saint Vincent and the Grenadines", "America/St_Vincent", "saint vincent grenadines america caribbean"),
    ("Grenada/Grenada", "America/Grenada", "grenada america caribbean"),
    ("Georgetown/Guyana", "America/Guyana", "guyana america south"),

    // --- AUSTRALIA & PACIFIC ---
    ("Sydney/Australia", "Australia/Sydney", "australia eastern aedt aest sydney melbourne brisbane canberra hobart gold coast newcastle wollongong"),
    ("Adelaide/Australia", "Australia/Adelaide", "australia central acst acdt adelaide darwin"),
    ("Perth/Australia", "Australia/Perth", "australia western awst perth"),
    ("Auckland/New Zealand", "Pacific/Auckland", "new zealand auckland wellington christchurch"),
    ("Apia/Samoa", "Pacific/Apia", "samoa pacific apia"),
    ("Majuro/Marshall Islands", "Pacific/Majuro", "marshall islands pacific majuro"),
    ("Port Moresby/Papua New Guinea", "Pacific/Port_Moresby", "papua new guinea pacific port moresby"),
    ("Palau/Palau", "Pacific/Palau", "palau pacific"),
    ("Guadalcanal/Solomon Islands", "Pacific/Guadalcanal", "solomon islands pacific guadalcanal"),
    ("Nauru/Nauru", "Pacific/Nauru", "nauru pacific"),
    ("Efate/Vanuatu", "Pacific/Efate", "vanuatu pacific efate"),
    ("Funafuti/Tuvalu", "Pacific/Funafuti", "tuvalu pacific funafuti"),
    ("Tongatapu/Tonga", "Pacific/Tongatapu", "tonga pacific tongatapu"),

    // --- AFRICA ---
    ("Cairo/Egypt", "Africa/Cairo", "egypt cairo alexandria giza"),
    ("Johannesburg/South Africa", "Africa/Johannesburg", "south africa johannesburg cape town durban pretoria"),
    ("Asmara/Eritrea", "Africa/Asmara", "eritrea africa asmara"),
    ("Addis Ababa/Ethiopia", "Africa/Addis_Ababa", "ethiopia africa addis ababa"),
    ("Gaborone/Botswana", "Africa/Gaborone", "botswana africa gaborone"),
    ("Algiers/Algeria", "Africa/Algiers", "algeria africa algiers"),
    ("Luanda/Angola", "Africa/Luanda", "angola africa luanda"),
    ("Bangui/Central African Republic", "Africa/Bangui", "central african republic africa bangui"),
    ("Ndjamena/Chad", "Africa/Ndjamena", "chad africa ndjamena"),
    ("Libreville/Gabon", "Africa/Libreville", "gabon africa libreville"),
    ("Banjul/Gambia", "Africa/Banjul", "gambia africa banjul"),
    ("Accra/Ghana", "Africa/Accra", "ghana africa accra"),
    ("Conakry/Guinea", "Africa/Conakry", "guinea africa conakry"),
    ("Bissau/Guinea-Bissau", "Africa/Bissau", "guinea bissau africa"),
    ("Kigali/Rwanda", "Africa/Kigali", "rwanda africa kigali"),
    ("Monrovia/Liberia", "Africa/Monrovia", "liberia africa monrovia"),
    ("Maseru/Lesotho", "Africa/Maseru", "lesotho africa maseru"),
    ("Tripoli/Libya", "Africa/Tripoli", "libya africa tripoli"),
    ("Nouakchott/Mauritania", "Africa/Nouakchott", "mauritania africa nouakchott"),
    ("Porto-Novo/Benin", "Africa/Porto-Novo", "benin africa porto novo"),
    ("Ouagadougou/Burkina Faso", "Africa/Ouagadougou", "burkina faso africa ouagadougou"),
    ("Maputo/Mozambique", "Africa/Maputo", "mozambique africa maputo"),
    ("Lusaka/Zambia", "Africa/Lusaka", "zambia africa lusaka"),
    ("Harare/Zimbabwe", "Africa/Harare", "zimbabwe africa harare"),
    ("Freetown/Sierra Leone", "Africa/Freetown", "sierra leone africa freetown"),
    ("Khartoum/Sudan", "Africa/Khartoum", "sudan africa khartoum"),
    ("Lome/Togo", "Africa/Lome", "togo africa lome"),
];


/// Timezone IANA ID to Abbreviation mapping
/// Format: (IANA_ID, Abbreviation)
pub const TIMEZONE_ABBREVIATIONS_MAP: &[(&str, &str)] = &[
    ("Kabul/Afghanistan", "AFT"),
    ("Tirana/Albania", "CET"),
    ("Algiers/Algeria", "CET"),
    ("Andorra/Andorra", "CET"),
    ("Luanda/Angola", "WAT"),
    ("St. John's/Antigua and Barbuda", "AST"),
    ("Buenos Aires/Argentina", "ART"),
    ("Yerevan/Armenia", "AMT"),
    ("Sydney/Australia", "AEDT"),
    ("Vienna/Austria", "CET"),
    ("Baku/Azerbaijan", "AZT"),
    ("Nassau/Bahamas", "EST"),
    ("Manama/Bahrain", "AST"),
    ("Dhaka/Bangladesh", "BST"),
    ("Bridgetown/Barbados", "AST"),
    ("Minsk/Belarus", "MSK"),
    ("Brussels/Belgium", "CET"),
    ("Belmopan/Belize", "CST"),
    ("Porto-Novo/Benin", "WAT"),
    ("Thimphu/Bhutan", "BTT"),
    ("La Paz/Bolivia", "BOT"),
    ("Sarajevo/Bosnia and Herzegovina", "CET"),
    ("Gaborone/Botswana", "CAT"),
    ("Brasília/Brazil", "BRT"),
    ("Bandar Seri Begawan/Brunei", "BNT"),
    ("Sofia/Bulgaria", "EET"),
    ("Ouagadougou/Burkina Faso", "GMT"),
    ("Bujumbura/Burundi", "CAT"),
    ("Praia/Cape Verde", "CVT"),
    ("Phnom Penh/Cambodia", "ICT"),
    ("Douala/Cameroon", "WAT"),
    ("Toronto/Canada", "EST"),
    ("Bangui/Central African Republic", "WAT"),
    ("N'Djamena/Chad", "WAT"),
    ("Santiago/Chile", "CLT"),
    ("Beijing/China", "CST"),
    ("Bogotá/Colombia", "COT"),
    ("Moroni/Comoros", "EAT"),
    ("Brazzaville/Congo", "WAT"),
    ("San José/Costa Rica", "CST"),
    ("Zagreb/Croatia", "CET"),
    ("Havana/Cuba", "CST"),
    ("Nicosia/Cyprus", "EET"),
    ("Prague/Czech Republic", "CET"),
    ("Copenhagen/Denmark", "CET"),
    ("Djibouti/Djibouti", "EAT"),
    ("Roseau/Dominica", "AST"),
    ("Santo Domingo/Dominican Republic", "AST"),
    ("Kinshasa/DR Congo", "WAT"),
    ("Guayaquil/Ecuador", "ECT"),
    ("Cairo/Egypt", "EET"),
    ("San Salvador/El Salvador", "CST"),
    ("Malabo/Equatorial Guinea", "WAT"),
    ("Asmara/Eritrea", "EAT"),
    ("Tallinn/Estonia", "EET"),
    ("Mbabane/Eswatini", "SAST"),
    ("Addis Ababa/Ethiopia", "EAT"),
    ("Suva/Fiji", "FJT"),
    ("Helsinki/Finland", "EET"),
    ("Paris/France", "CET"),
    ("Libreville/Gabon", "WAT"),
    ("Banjul/Gambia", "GMT"),
    ("Tbilisi/Georgia", "GET"),
    ("Berlin/Germany", "CET"),
    ("Accra/Ghana", "GMT"),
    ("Athens/Greece", "EET"),
    ("St. George's/Grenada", "AST"),
    ("Guatemala City/Guatemala", "CST"),
    ("Conakry/Guinea", "GMT"),
    ("Bissau/Guinea-Bissau", "GMT"),
    ("Georgetown/Guyana", "GYT"),
    ("Port-au-Prince/Haiti", "EST"),
    ("Tegucigalpa/Honduras", "CST"),
    ("Budapest/Hungary", "CET"),
    ("Reykjavik/Iceland", "GMT"),
    ("New Delhi/India", "IST"),
    ("Jakarta/Indonesia", "WIB"),
    ("Tehran/Iran", "IRST"),
    ("Baghdad/Iraq", "AST"),
    ("Dublin/Ireland", "GMT"),
    ("Jerusalem/Israel", "IST"),
    ("Rome/Italy", "CET"),
    ("Kingston/Jamaica", "EST"),
    ("Tokyo/Japan", "JST"),
    ("Amman/Jordan", "EET"),
    ("Almaty/Kazakhstan", "ALMT"),
    ("Nairobi/Kenya", "EAT"),
    ("Tarawa/Kiribati", "GILT"),
    ("Kuwait City/Kuwait", "AST"),
    ("Bishkek/Kyrgyzstan", "KGT"),
    ("Vientiane/Laos", "ICT"),
    ("Riga/Latvia", "EET"),
    ("Beirut/Lebanon", "EET"),
    ("Maseru/Lesotho", "SAST"),
    ("Monrovia/Liberia", "GMT"),
    ("Tripoli/Libya", "EET"),
    ("Vaduz/Liechtenstein", "CET"),
    ("Vilnius/Lithuania", "EET"),
    ("Luxembourg/Luxembourg", "CET"),
    ("Antananarivo/Madagascar", "EAT"),
    ("Blantyre/Malawi", "CAT"),
    ("Kuala Lumpur/Malaysia", "MYT"),
    ("Malé/Maldives", "MVT"),
    ("Bamako/Mali", "GMT"),
    ("Valletta/Malta", "CET"),
    ("Majuro/Marshall Islands", "MHT"),
    ("Nouakchott/Mauritania", "GMT"),
    ("Port Louis/Mauritius", "MUT"),
    ("Mexico City/Mexico", "CST"),
    ("Pohnpei/Micronesia", "PONT"),
    ("Chișinău/Moldova", "EET"),
    ("Monaco/Monaco", "CET"),
    ("Ulaanbaatar/Mongolia", "ULAT"),
    ("Podgorica/Montenegro", "CET"),
    ("Rabat/Morocco", "WET"),
    ("Maputo/Mozambique", "CAT"),
    ("Yangon/Myanmar", "MMT"),
    ("Windhoek/Namibia", "CAT"),
    ("Nauru/Nauru", "NRT"),
    ("Kathmandu/Nepal", "NPT"),
    ("Amsterdam/Netherlands", "CET"),
    ("Auckland/New Zealand", "NZDT"),
    ("Managua/Nicaragua", "CST"),
    ("Niamey/Niger", "WAT"),
    ("Lagos/Nigeria", "WAT"),
    ("Pyongyang/North Korea", "KST"),
    ("Skopje/North Macedonia", "CET"),
    ("Oslo/Norway", "CET"),
    ("Muscat/Oman", "GST"),
    ("Karachi/Pakistan", "PKT"),
    ("Ngerulmud/Palau", "PWT"),
    ("Hebron/Palestine", "EET"),
    ("Panama City/Panama", "EST"),
    ("Port Moresby/Papua New Guinea", "PGT"),
    ("Asunción/Paraguay", "PYT"),
    ("Lima/Peru", "PET"),
    ("Manila/Philippines", "PHT"),
    ("Warsaw/Poland", "CET"),
    ("Lisbon/Portugal", "WET"),
    ("Doha/Qatar", "AST"),
    ("Bucharest/Romania", "EET"),
    ("Moscow/Russia", "MSK"),
    ("Kigali/Rwanda", "CAT"),
    ("Basseterre/Saint Kitts and Nevis", "AST"),
    ("Castries/Saint Lucia", "AST"),
    ("Kingstown/Saint Vincent and the Grenadines", "AST"),
    ("Apia/Samoa", "WST"),
    ("San Marino/San Marino", "CET"),
    ("Riyadh/Saudi Arabia", "AST"),
    ("Dakar/Senegal", "GMT"),
    ("Belgrade/Serbia", "CET"),
    ("Victoria/Seychelles", "SCT"),
    ("Freetown/Sierra Leone", "GMT"),
    ("Singapore/Singapore", "SGT"),
    ("Bratislava/Slovakia", "CET"),
    ("Ljubljana/Slovenia", "CET"),
    ("Honiara/Solomon Islands", "SBT"),
    ("Mogadishu/Somalia", "EAT"),
    ("Johannesburg/South Africa", "SAST"),
    ("Seoul/South Korea", "KST"),
    ("Juba/South Sudan", "EAT"),
    ("Madrid/Spain", "CET"),
    ("Colombo/Sri Lanka", "IST"),
    ("Khartoum/Sudan", "CAT"),
    ("Paramaribo/Suriname", "SRT"),
    ("Stockholm/Sweden", "CET"),
    ("Zurich/Switzerland", "CET"),
    ("Damascus/Syria", "EET"),
    ("Taipei/Taiwan", "CST"),
    ("Dushanbe/Tajikistan", "TJT"),
    ("Dar es Salaam/Tanzania", "EAT"),
    ("Bangkok/Thailand", "ICT"),
    ("Dili/Timor-Leste", "TLT"),
    ("Lomé/Togo", "GMT"),
    ("Nuku'alofa/Tonga", "TOT"),
    ("Port of Spain/Trinidad and Tobago", "AST"),
    ("Tunis/Tunisia", "CET"),
    ("Istanbul/Turkey", "TRT"),
    ("Ashgabat/Turkmenistan", "TMT"),
    ("Funafuti/Tuvalu", "TVT"),
    ("Kampala/Uganda", "EAT"),
    ("Kyiv/Ukraine", "EET"),
    ("Dubai/United Arab Emirates", "GST"),
    ("London/United Kingdom", "GMT"),
    ("New York/United States", "EST"),
    ("Montevideo/Uruguay", "UYT"),
    ("Tashkent/Uzbekistan", "UZT"),
    ("Port Vila/Vanuatu", "VUT"),
    ("Vatican City/Vatican", "CET"),
    ("Caracas/Venezuela", "VET"),
    ("Ho Chi Minh City/Vietnam", "ICT"),
    ("Aden/Yemen", "AST"),
    ("Lusaka/Zambia", "CAT"),
    ("Harare/Zimbabwe", "CAT"),
];


/// Get timezone abbreviation for a given IANA ID
pub fn get_timezone_abbreviation(iana_id: &str) -> &str {
    // First, find the display label for this IANA ID
    let display_label = ALL_TIMEZONES
        .iter()
        .find(|(_, id, _)| *id == iana_id)
        .map(|(label, _, _)| *label);
    
    // Then look up the abbreviation using the display label
    if let Some(label) = display_label {
        TIMEZONE_ABBREVIATIONS_MAP
            .iter()
            .find(|(map_label, _)| *map_label == label)
            .map(|(_, abbr)| *abbr)
            .unwrap_or("UTC")
    } else {
        "UTC"
    }
}
