// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSettings, ClipboardHistoryItem } from "../logic/types";


export type AppEvent =
    | { event: "clipboard://updated", payload: ClipboardHistoryItem }
    | { event: "settings://updated", payload: AppSettings }
    | { event: "window://focus-changed", payload: boolean };
