// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiKeys = { translation_provider: string, translation_key: string, google_translate_api_key: string, currency_api_key: string, };

export type AppSettings = { hotkeys: HotkeySettings, api_keys: ApiKeys, preferences: UserPreferences, };

export type HotkeySettings = { command_palette: string, };

export type UserPreferences = { default_source_lang: string, default_target_lang: string, default_currency_from: string, default_currency_to: string, theme: string, };
